service: currenpy

provider:
  name: aws
  runtime: python2.7
  memorySize: 128
  region: eu-west-1

functions:
  convert:
    handler: handler.convert
    events:
      - http:
          path: convert/{from}/{to}/{amount}
          method: get

plugins:
  - serverless-python-requirements
